# SPDX-License-Identifier: LicenseRef-NON-AI-CC0-1.0
# SPDX-FileCopyrightText: Lee Cannon <leecannon@leecannon.xyz>

version = 1
SPDX-PackageName = "CascadeOS"
SPDX-PackageSupplier = "Lee Cannon <leecannon@leecannon.xyz>"
SPDX-PackageDownloadLocation = "https://github.com/CascadeOS/CascadeOS"

[[annotations]]
path = "**.md"
precedence = "aggregate"
SPDX-License-Identifier = "LicenseRef-NON-AI-CC0-1.0"
SPDX-FileCopyrightText = "Lee Cannon <leecannon@leecannon.xyz>"

[[annotations]]
path = ".assets/justforfunnoreally_dev.svg"
precedence = "aggregate"
SPDX-License-Identifier = "CC0-1.0"
SPDX-FileCopyrightText = "https://shields.io/>"

[[annotations]]
path = ".assets/no_ai.svg"
precedence = "aggregate"
SPDX-License-Identifier = "CC0-1.0"
SPDX-FileCopyrightText = "https://shields.io/"

[[annotations]]
path = "kernel/kernel/init/output/ter-v14n.sfn"
precedence = "aggregate"
SPDX-License-Identifier = "OFL-1.1-RFN"
SPDX-FileCopyrightText = "Copyright (C) 2020 Dimitar Toshkov Zhekov, with Reserved Font Name \"Terminus Font\"."
